language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - php vendor/bin/php-cs-fixer fix lib/ --dry-run --diff
  - php vendor/bin/phpstan analyse -c phpstan.neon lib tests
  - php vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
